NEW 
1 ' EMOTICONS, REF: https://fr.wikipedia.org/wiki/Art_ASCII
5 CLS:?"EMOTICONS"
10 ? "(^_^)  sourire homme, (^.^)  sourire femme."
20 ? "d~.~b  ecoute au casque."
30 ? "-_-  exaspere, fatigue."
40 ? "\(^O^)/  heureux/panique."
50 ? "X_X  mort."
60 ? "(o.~) ou ^_-  (clin d'œil)."
70 ? "-_-'  (gene - par quelqu'un)."
80 ? "^_^  (content)."
90 ? "(*^_^*)  (rougit, timide)."
100 ? "(-_-)ZZZ  (dort)."
110 ? "-`(0_o)´- ou  O_o   (perplexe)."
120 ? "``(ToT)´´  (pleure)."
130 ? "(!_!) ou (o_o)  (choque)." 
140 ? "(?_?)  (confus)."
150 ? "(|_ |)  (dépité)."
160 ? "(-_-)  (blasé)."
170 ? "(I_ I)  (suspicieux)."
180 ? ">(°< °)<  ou  \_/o<  (oiseau)."
